// Will Healthcare - Updated Master Product Catalog Data (62 Products)
const WILL_PRODUCTS = [
  {
    "id": "p01",
    "name": "Prin-G Lotion",
    "composition": "Permethrin 5% w/v",
    "category": "lotions",
    "packing": "100 ml",
    "badge": "Anti-Parasitic Lotion",
    "image": "products/product_04.jpeg",
    "imageVerified": true,
    "description": "Topical scabicidal and pediculicidal lotion for rapid relief from scabies and lice.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p02",
    "name": "Prin-G Soap",
    "composition": "Permethrin 1%",
    "category": "soaps",
    "packing": "75 g",
    "badge": "Medicated Soap",
    "image": "products/product_02.jpeg",
    "imageVerified": true,
    "description": "Therapeutic cleansing bar formulated for managing scabies and skin mites.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p03",
    "name": "W-Bact Ointment",
    "composition": "Mupirocin 2% w/w",
    "category": "creams",
    "packing": "10 g",
    "badge": "Antibacterial Ointment",
    "image": "products/product_07.jpeg",
    "imageVerified": true,
    "description": "Broad-spectrum topical antibacterial ointment targeting primary and secondary skin infections.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p04",
    "name": "Super-GM",
    "composition": "Clobetasol + Neomycin + Miconazole + Zinc Oxide + Borax + Chlorocresol",
    "category": "creams",
    "packing": "15 g",
    "badge": "Dermatology & Skin Care",
    "image": "products/mockup_supergm_cream.jpg",
    "imageVerified": true,
    "description": "Clobetasol + Neomycin + Miconazole + Zinc Oxide + Borax + Chlorocresol in 15 g commercial packing.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p05",
    "name": "Furomom Cream",
    "composition": "Mometasone Furoate 0.1%",
    "category": "creams",
    "packing": "15 g",
    "badge": "Topical Corticosteroid",
    "image": "",
    "imageVerified": false,
    "description": "Medium-potency topical steroid cream for inflammatory and pruritic manifestations of dermatoses.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p06",
    "name": "Furomom-S",
    "composition": "Mometasone Furoate 0.1% + Salicylic Acid 3%",
    "category": "creams",
    "packing": "20 g",
    "badge": "Keratolytic Derma Ointment",
    "image": "",
    "imageVerified": false,
    "description": "Synergistic combination of potent steroid and keratolytic salicylic acid for hyperkeratotic plaque psoriasis.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p07",
    "name": "Furo-Forte",
    "composition": "Mometasone 0.1% + Terbinafine 1%",
    "category": "creams",
    "packing": "15 g",
    "badge": "Dual Action Derma Cream",
    "image": "",
    "imageVerified": false,
    "description": "Advanced anti-inflammatory and allylamine antifungal cream for stubborn dermatophyte infections.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p08",
    "name": "Cliroft-Wil Gel",
    "composition": "Clindamycin Phosphate 1% + Nicotinamide 4%",
    "category": "gels",
    "packing": "15 g",
    "badge": "Anti-Acne Gel",
    "image": "",
    "imageVerified": false,
    "description": "Topical antibiotic and anti-inflammatory vitamin gel tackling inflammatory acne vulgaris.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p09",
    "name": "Adwil-C",
    "composition": "Adapalene 0.1% + Clindamycin Phosphate 1%",
    "category": "gels",
    "packing": "15 g",
    "badge": "Dermatology & Skin Care",
    "image": "",
    "imageVerified": false,
    "description": "Adapalene 0.1% + Clindamycin Phosphate 1% in 15 g commercial packing.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p10",
    "name": "Desowil Cream",
    "composition": "Desonide 0.05%",
    "category": "creams",
    "packing": "15 g",
    "badge": "Gentle Corticosteroid",
    "image": "",
    "imageVerified": false,
    "description": "Mild topical steroid tailored for sensitive facial skin, pediatric atopic dermatitis, and intertriginous areas.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p11",
    "name": "Luwil Cream",
    "composition": "Luliconazole 1%",
    "category": "creams",
    "packing": "15 g",
    "badge": "Potent Antifungal",
    "image": "",
    "imageVerified": false,
    "description": "Broad-spectrum imidazole antifungal cream with once-daily dosing efficacy against tinea infections.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p12",
    "name": "Clowil Dusting Powder",
    "composition": "Clotrimazole 1%",
    "category": "powders",
    "packing": "100 g",
    "badge": "Antifungal Dusting Powder",
    "image": "",
    "imageVerified": false,
    "description": "Absorbent antifungal dusting powder for soothing relief from sweat rash, fungal itch, and prickly heat.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p13",
    "name": "Wil-Lacto Lotion",
    "composition": "Calamine + Zinc Oxide + Bentonite + Glycerine + Sodium Citrate",
    "category": "lotions",
    "packing": "60 ml",
    "badge": "Soothing Calamine Lotion",
    "image": "",
    "imageVerified": false,
    "description": "Protective soothing emulsion providing cooling comfort for sunburns, insect bites, and allergic rashes.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p14",
    "name": "Ace-G Shampoo",
    "composition": "Ketoconazole 2% + Zinc Pyrithione 1%",
    "category": "lotions",
    "packing": "100 ml",
    "badge": "Dermatology & Skin Care",
    "image": "products/mockup_aceg_shampoo.jpg",
    "imageVerified": true,
    "description": "Ketoconazole 2% + Zinc Pyrithione 1% in 100 ml commercial packing.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p15",
    "name": "Ace-G Soap",
    "composition": "Ketoconazole 2%",
    "category": "soaps",
    "packing": "75 g",
    "badge": "Antifungal Medicated Soap",
    "image": "",
    "imageVerified": false,
    "description": "Daily antimicrobial hygiene bar eliminating pityriasis versicolor, candidiasis, and fungal body odor.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p16",
    "name": "V-50 Sunscreen Lotion",
    "composition": "SPF 50, PA+++",
    "category": "lotions",
    "packing": "100 ml",
    "badge": "Dermatology & Skin Care",
    "image": "products/mockup_v50_sunscreen.jpg",
    "imageVerified": true,
    "description": "SPF 50, PA+++ in 100 ml commercial packing.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p17",
    "name": "Etasol Cream",
    "composition": "Clobetasol Propionate 0.05%",
    "category": "creams",
    "packing": "15 g",
    "badge": "High Potency Derma Cream",
    "image": "",
    "imageVerified": false,
    "description": "Super-potent class-I corticosteroid cream for resistant recalcitrant dermatoses, eczema, and psoriasis.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p18",
    "name": "ELUZ Premium Moisturizing Cream",
    "composition": "Hyaluronic Acid 2% + Liquid Paraffin 6% + White Soft Paraffin 15% + Aloe Vera 3% + Vitamin E Acetate 1%",
    "category": "creams",
    "packing": "100 ml",
    "badge": "Deep Hydration Barrier",
    "image": "",
    "imageVerified": false,
    "description": "Ceramide-mimicking emollient formulation replenishing dry, compromised skin barriers.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p19",
    "name": "Light Cream",
    "composition": "Hydroquinone 4%",
    "category": "creams",
    "packing": "30 g",
    "badge": "Depigmentation Therapy",
    "image": "",
    "imageVerified": false,
    "description": "Clinical strength tyrosinase inhibitor cream targeting melasma, chloasma, and hyperpigmentation.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p20",
    "name": "Bioglow-G Soap",
    "composition": "Glutathione + Kojic Acid; TFM 76%; pH 5.5",
    "category": "soaps",
    "packing": "75 g",
    "badge": "Skin Glow Cleansing Soap",
    "image": "",
    "imageVerified": false,
    "description": "Antioxidant-rich cosmetic beauty soap promoting luminous even-toned skin and radical scavenging.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p21",
    "name": "Bioglow-G Face Wash",
    "composition": "Glutathione + Kojic Acid; pH 5.5",
    "category": "lotions",
    "packing": "100 ml",
    "badge": "Gentle Brightening Cleanser",
    "image": "",
    "imageVerified": false,
    "description": "Deep-cleansing foaming wash lifting impurities while infusing cell-protective antioxidants.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p22",
    "name": "Hair Growth Serum",
    "composition": "Redensyl-based formulation",
    "category": "serums",
    "packing": "70 ml",
    "badge": "Dermatology & Skin Care",
    "image": "products/mockup_hair_serum.jpg",
    "imageVerified": true,
    "description": "Redensyl-based formulation in 70 ml commercial packing.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p23",
    "name": "Hair Growth Solution",
    "composition": "Minoxidil 5% + Finasteride 0.1%",
    "category": "serums",
    "packing": "60 ml",
    "badge": "Targeted Trichology Solution",
    "image": "",
    "imageVerified": false,
    "description": "Dual-action vasodilator and 5-alpha reductase inhibitor arresting hair loss and stimulating follicular regrowth.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "DERMATOLOGY / SKIN CARE"
  },
  {
    "id": "p24",
    "name": "Wilzo-500",
    "composition": "Azithromycin 500 mg",
    "category": "tablets",
    "packing": "10×5",
    "badge": "Tablets",
    "image": "",
    "imageVerified": false,
    "description": "Azithromycin 500 mg in 10×5 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "TABLETS"
  },
  {
    "id": "p25",
    "name": "ACWIL-625",
    "composition": "Amoxicillin 500 mg + Clavulanic Acid 125 mg + Lactic Acid Bacillus",
    "category": "tablets",
    "packing": "10×6",
    "badge": "Tablets",
    "image": "",
    "imageVerified": false,
    "description": "Amoxicillin 500 mg + Clavulanic Acid 125 mg + Lactic Acid Bacillus in 10×6 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "TABLETS"
  },
  {
    "id": "p26",
    "name": "Wilcef-L",
    "composition": "Cefixime 200 mg + Lactobacillus",
    "category": "tablets",
    "packing": "10×10",
    "badge": "Tablets",
    "image": "",
    "imageVerified": false,
    "description": "Cefixime 200 mg + Lactobacillus in 10×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "TABLETS"
  },
  {
    "id": "p27",
    "name": "Flash-200",
    "composition": "Ofloxacin 200 mg",
    "category": "tablets",
    "packing": "10×10",
    "badge": "Tablets",
    "image": "",
    "imageVerified": false,
    "description": "Ofloxacin 200 mg in 10×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "TABLETS"
  },
  {
    "id": "p28",
    "name": "Flash-OZ",
    "composition": "Ofloxacin 200 mg + Ornidazole 500 mg",
    "category": "tablets",
    "packing": "10×10",
    "badge": "Tablets",
    "image": "",
    "imageVerified": false,
    "description": "Ofloxacin 200 mg + Ornidazole 500 mg in 10×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "TABLETS"
  },
  {
    "id": "p29",
    "name": "Wilace-SP",
    "composition": "Aceclofenac 100 mg + Paracetamol 325 mg + Serratiopeptidase 15 mg",
    "category": "tablets",
    "packing": "10×10",
    "badge": "Triple Action Analgesic",
    "image": "products/mockup_wilace_sp.jpg",
    "imageVerified": true,
    "description": "Potent NSAID, antipyretic, and proteolytic enzyme combination for acute trauma, post-surgery pain, and osteoarthritis.",
    "manufacturer": "Savya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "TABLETS"
  },
  {
    "id": "p30",
    "name": "Netika-P",
    "composition": "Diclofenac Potassium 50 mg + Paracetamol 325 mg + Serratiopeptidase 15 mg",
    "category": "tablets",
    "packing": "5×2×10",
    "badge": "Anti-Inflammatory & Edema Reducer",
    "image": "products/product_35.jpeg",
    "imageVerified": true,
    "description": "Rapidly absorbed potassium diclofenac with paracetamol and serratiopeptidase to quickly reduce inflammation and swelling.",
    "manufacturer": "Savya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "TABLETS"
  },
  {
    "id": "p31",
    "name": "Tramwil-MF",
    "composition": "Drotaverine HCl 80 mg + Mefenamic Acid 250 mg",
    "category": "tablets",
    "packing": "10×10",
    "badge": "Tablets",
    "image": "",
    "imageVerified": false,
    "description": "Drotaverine HCl 80 mg + Mefenamic Acid 250 mg in 10×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "TABLETS"
  },
  {
    "id": "p32",
    "name": "PRSM-6",
    "composition": "Deflazacort 6 mg",
    "category": "tablets",
    "packing": "10×10",
    "badge": "Tablets",
    "image": "",
    "imageVerified": false,
    "description": "Deflazacort 6 mg in 10×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "TABLETS"
  },
  {
    "id": "p33",
    "name": "Wilrab-20",
    "composition": "Rabeprazole 20 mg",
    "category": "tablets",
    "packing": "10×10",
    "badge": "Tablets",
    "image": "",
    "imageVerified": false,
    "description": "Rabeprazole 20 mg in 10×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "TABLETS"
  },
  {
    "id": "p34",
    "name": "G-Dex-20",
    "composition": "Duloxetine equivalent to 20 mg",
    "category": "tablets",
    "packing": "10×10",
    "badge": "Tablets",
    "image": "",
    "imageVerified": false,
    "description": "Duloxetine equivalent to 20 mg in 10×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "TABLETS"
  },
  {
    "id": "p35",
    "name": "Wilcal",
    "composition": "Calcium Citrate + Magnesium + Vitamin D3 + Zinc",
    "category": "tablets",
    "packing": "10×15",
    "badge": "Advanced Calcium Complex",
    "image": "products/product_51.jpeg",
    "imageVerified": true,
    "description": "High-absorption calcium citrate formula with synergistic minerals and vitamin D3 for comprehensive bone density.",
    "manufacturer": "Savya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "TABLETS"
  },
  {
    "id": "p36",
    "name": "Wildex-LB",
    "composition": "Doxycycline 100 mg + Lactic Acid Bacillus",
    "category": "capsules",
    "packing": "10×10",
    "badge": "Antibiotic + Probiotic",
    "image": "products/product_45.jpeg",
    "imageVerified": true,
    "description": "Broad-spectrum antibacterial paired with gut-protective probiotic spores to prevent diarrhea.",
    "manufacturer": "Savya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "CAPSULES / SOFTGELS"
  },
  {
    "id": "p37",
    "name": "Bionerve-Forte",
    "composition": "Methylcobalamin 750 mcg + Pregabalin 75 mg",
    "category": "capsules",
    "packing": "10×10",
    "badge": "Capsules & Softgels",
    "image": "products/product_28.jpeg",
    "imageVerified": true,
    "description": "Methylcobalamin 750 mcg + Pregabalin 75 mg in 10×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "CAPSULES / SOFTGELS"
  },
  {
    "id": "p38",
    "name": "Wilrab-DSR",
    "composition": "Rabeprazole 20 mg + Domperidone SR 30 mg",
    "category": "capsules",
    "packing": "10×10",
    "badge": "Proton Pump Inhibitor + Prokinetic",
    "image": "products/product_41.jpeg",
    "imageVerified": true,
    "description": "Comprehensive dual-release capsule for GERD, hyperacidity, peptic ulceration, and associated nausea.",
    "manufacturer": "Savya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "CAPSULES / SOFTGELS"
  },
  {
    "id": "p39",
    "name": "Prefast-DSR",
    "composition": "Pantoprazole 40 mg + Domperidone SR 30 mg",
    "category": "capsules",
    "packing": "10×10",
    "badge": "Capsules & Softgels",
    "image": "products/product_18.jpeg",
    "imageVerified": true,
    "description": "Pantoprazole 40 mg + Domperidone SR 30 mg in 10×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "CAPSULES / SOFTGELS"
  },
  {
    "id": "p40",
    "name": "Itrawil-100",
    "composition": "Itraconazole 100 mg",
    "category": "capsules",
    "packing": "10×10",
    "badge": "Capsules & Softgels",
    "image": "",
    "imageVerified": false,
    "description": "Itraconazole 100 mg in 10×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "CAPSULES / SOFTGELS"
  },
  {
    "id": "p41",
    "name": "Prewil",
    "composition": "Lycopene + Vitamins/Minerals + L-Lysine",
    "category": "capsules",
    "packing": "10×10",
    "badge": "Capsules & Softgels",
    "image": "products/product_19.jpeg",
    "imageVerified": true,
    "description": "Lycopene + Vitamins/Minerals + L-Lysine in 10×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "CAPSULES / SOFTGELS"
  },
  {
    "id": "p42",
    "name": "Prewil-OMG",
    "composition": "Omega-3 + Multivitamins",
    "category": "capsules",
    "packing": "10×1×10",
    "badge": "Capsules & Softgels",
    "image": "products/product_20.jpeg",
    "imageVerified": true,
    "description": "Omega-3 + Multivitamins in 10×1×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "CAPSULES / SOFTGELS"
  },
  {
    "id": "p43",
    "name": "Wilcal Strong",
    "composition": "Calcitriol + Calcium Carbonate + Methylcobalamin + K7 + Zinc + Magnesium",
    "category": "capsules",
    "packing": "10×1×10",
    "badge": "Capsules & Softgels",
    "image": "",
    "imageVerified": false,
    "description": "Calcitriol + Calcium Carbonate + Methylcobalamin + K7 + Zinc + Magnesium in 10×1×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "CAPSULES / SOFTGELS"
  },
  {
    "id": "p44",
    "name": "Prewil Q10",
    "composition": "CoQ10 + antioxidants",
    "category": "capsules",
    "packing": "10×1×10",
    "badge": "Capsules & Softgels",
    "image": "",
    "imageVerified": false,
    "description": "CoQ10 + antioxidants in 10×1×10 commercial packing.",
    "manufacturer": "Saavya Pharmaceuticals",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "CAPSULES / SOFTGELS"
  },
  {
    "id": "p45",
    "name": "Wilcof-D",
    "composition": "Dextromethorphan + Phenylephrine + Chlorpheniramine",
    "category": "syrups",
    "packing": "100 ml",
    "badge": "Syrups & Oral Liquids",
    "image": "products/mockup_wilcof_d.jpg",
    "imageVerified": true,
    "description": "Dextromethorphan + Phenylephrine + Chlorpheniramine in 100 ml commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "SYRUPS / ORAL LIQUIDS"
  },
  {
    "id": "p46",
    "name": "Wilcof-A",
    "composition": "Ambroxol + Terbutaline + Guaiphenesin + Menthol",
    "category": "syrups",
    "packing": "100 ml",
    "badge": "Syrups & Oral Liquids",
    "image": "products/product_08.jpeg",
    "imageVerified": true,
    "description": "Ambroxol + Terbutaline + Guaiphenesin + Menthol in 100 ml commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "SYRUPS / ORAL LIQUIDS"
  },
  {
    "id": "p47",
    "name": "Wilcof-LS",
    "composition": "Levosalbutamol + Ambroxol + Guaiphenesin",
    "category": "syrups",
    "packing": "100 ml",
    "badge": "Syrups & Oral Liquids",
    "image": "products/product_03.jpeg",
    "imageVerified": true,
    "description": "Levosalbutamol + Ambroxol + Guaiphenesin in 100 ml commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "SYRUPS / ORAL LIQUIDS"
  },
  {
    "id": "p48",
    "name": "Wilzo-LMG",
    "composition": "Levocetirizine + Montelukast",
    "category": "syrups",
    "packing": "60 ml",
    "badge": "Syrups & Oral Liquids",
    "image": "",
    "imageVerified": false,
    "description": "Levocetirizine + Montelukast in 60 ml commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "SYRUPS / ORAL LIQUIDS"
  },
  {
    "id": "p49",
    "name": "PRSM-6 Suspension",
    "composition": "Deflazacort",
    "category": "syrups",
    "packing": "30 ml",
    "badge": "Syrups & Oral Liquids",
    "image": "products/product_05.jpeg",
    "imageVerified": true,
    "description": "Deflazacort in 30 ml commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "SYRUPS / ORAL LIQUIDS"
  },
  {
    "id": "p50",
    "name": "Willmox-DS",
    "composition": "Amoxicillin + Clavulanic Acid",
    "category": "syrups",
    "packing": "30 ml",
    "badge": "Syrups & Oral Liquids",
    "image": "",
    "imageVerified": false,
    "description": "Amoxicillin + Clavulanic Acid in 30 ml commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "SYRUPS / ORAL LIQUIDS"
  },
  {
    "id": "p51",
    "name": "AL-KA-1",
    "composition": "Disodium Hydrogen Citrate",
    "category": "syrups",
    "packing": "100 ml",
    "badge": "Syrups & Oral Liquids",
    "image": "",
    "imageVerified": false,
    "description": "Disodium Hydrogen Citrate in 100 ml commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "SYRUPS / ORAL LIQUIDS"
  },
  {
    "id": "p52",
    "name": "Biocyp Forte Syrup",
    "composition": "Cyproheptadine-based nutritional/appetite formulation",
    "category": "syrups",
    "packing": "—",
    "badge": "Syrups & Oral Liquids",
    "image": "",
    "imageVerified": false,
    "description": "Cyproheptadine-based nutritional/appetite formulation in — commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "SYRUPS / ORAL LIQUIDS"
  },
  {
    "id": "p53",
    "name": "Wilzyme Syrup",
    "composition": "Fungal Diastase + Pepsin",
    "category": "syrups",
    "packing": "200 ml",
    "badge": "Syrups & Oral Liquids",
    "image": "",
    "imageVerified": false,
    "description": "Fungal Diastase + Pepsin in 200 ml commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "SYRUPS / ORAL LIQUIDS"
  },
  {
    "id": "p54",
    "name": "RxW OXID-G Protein Powder",
    "composition": "Protein 15% + vitamins/minerals; sugar-free",
    "category": "nutraceuticals",
    "packing": "200 g",
    "badge": "Nutrition & Personal Care",
    "image": "",
    "imageVerified": false,
    "description": "Protein 15% + vitamins/minerals; sugar-free in 200 g commercial packing.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "NUTRITION / PERSONAL CARE"
  },
  {
    "id": "p55",
    "name": "WILL-Wash",
    "composition": "Triclosan + Lactic Acid + Aloe Vera",
    "category": "lotions",
    "packing": "100 ml",
    "badge": "Nutrition & Personal Care",
    "image": "",
    "imageVerified": false,
    "description": "Triclosan + Lactic Acid + Aloe Vera in 100 ml commercial packing.",
    "manufacturer": "Biowil Formulation",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "NUTRITION / PERSONAL CARE"
  },
  {
    "id": "p56",
    "name": "Relax Anti Piles Capsules",
    "composition": "Katha Extract 125 mg + Ritha Tavak Bhasma 125 mg + Kuda Chhal Extract 100 mg + Rasont 50 mg + Kutki 50 mg + Neem 50 mg",
    "category": "ayurvedic",
    "packing": "10×10",
    "badge": "Ayush",
    "image": "",
    "imageVerified": false,
    "description": "Katha Extract 125 mg + Ritha Tavak Bhasma 125 mg + Kuda Chhal Extract 100 mg + Rasont 50 mg + Kutki 50 mg + Neem 50 mg in 10×10 commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "AYUSH"
  },
  {
    "id": "p57",
    "name": "Wilcrux Cap",
    "composition": "Ayurvedic multi-herbal formulation",
    "category": "ayurvedic",
    "packing": "10×10",
    "badge": "Ayush",
    "image": "",
    "imageVerified": false,
    "description": "Ayurvedic multi-herbal formulation in 10×10 commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "AYUSH"
  },
  {
    "id": "p58",
    "name": "Wil-Liv Syrup",
    "composition": "Ayurvedic liver-support herbal formulation",
    "category": "ayurvedic",
    "packing": "200 ml",
    "badge": "Herbal Hepato-Protective Tonic",
    "image": "",
    "imageVerified": false,
    "description": "Fortified hepatoprotective herbal syrup restoring liver enzymes, relieving loss of appetite, and aiding digestion.",
    "manufacturer": "Aries Drugs",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "AYUSH"
  },
  {
    "id": "p59",
    "name": "WILLIV Syrup",
    "composition": "Ayurvedic liver wellness formulation",
    "category": "ayurvedic",
    "packing": "200 ml",
    "badge": "Herbal Hepato-Protective Tonic",
    "image": "",
    "imageVerified": false,
    "description": "Fortified hepatoprotective herbal syrup restoring liver enzymes, relieving loss of appetite, and aiding digestion.",
    "manufacturer": "Aries Drugs",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "AYUSH"
  },
  {
    "id": "p60",
    "name": "WILLIV-DS Capsule",
    "composition": "Ayurvedic formulation",
    "category": "ayurvedic",
    "packing": "10×10",
    "badge": "Ayush",
    "image": "",
    "imageVerified": false,
    "description": "Ayurvedic formulation in 10×10 commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "AYUSH"
  },
  {
    "id": "p61",
    "name": "Ortho-G Oil",
    "composition": "Ayurvedic herbal joint/muscle pain oil",
    "category": "ayurvedic",
    "packing": "60 ml",
    "badge": "Ayush",
    "image": "",
    "imageVerified": false,
    "description": "Ayurvedic herbal joint/muscle pain oil in 60 ml commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "AYUSH"
  },
  {
    "id": "p62",
    "name": "Wellfit Massage Oil",
    "composition": "Arachis Oil 25% + Sunflower Oil 65% + Olive Oil 10%",
    "category": "ayurvedic",
    "packing": "100 ml",
    "badge": "Ayush",
    "image": "",
    "imageVerified": false,
    "description": "Arachis Oil 25% + Sunflower Oil 65% + Olive Oil 10% in 100 ml commercial packing.",
    "manufacturer": "Aries Drugs Pvt. Ltd.",
    "marketer": "Will Healthcare Pvt. Ltd.",
    "catalogSection": "AYUSH"
  }
];

if (typeof window !== 'undefined') { window.WILL_PRODUCTS = WILL_PRODUCTS; }
if (typeof module !== 'undefined' && module.exports) { module.exports = WILL_PRODUCTS; }
